# Generated by Django 3.0.7 on 2020-06-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=100)),
                ('item_vpn', models.CharField(max_length=10)),
                ('item_crc', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_desc', models.CharField(max_length=20)),
            ],
        ),
    ]
