# Generated by Django 3.0.7 on 2020-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200630_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_displayed',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
