# Generated by Django 3.0.7 on 2020-07-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_item_is_displayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='list_of_items',
        ),
        migrations.AddField(
            model_name='checklist',
            name='list_of_items',
            field=models.ManyToManyField(to='list.item'),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='list_of_pop',
        ),
        migrations.AddField(
            model_name='checklist',
            name='list_of_pop',
            field=models.ManyToManyField(to='list.pop'),
        ),
    ]
