# Generated by Django 3.0.7 on 2020-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200703_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='pop_is_displayed',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=1),
        ),
    ]
