# Generated by Django 3.0.7 on 2020-07-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_remove_item_is_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_displayed',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=1),
        ),
    ]
