# Generated by Django 3.0.7 on 2020-07-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_item_is_displayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_displayed',
            new_name='item_is_displayed',
        ),
    ]
