# Generated by Django 3.0.7 on 2020-07-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20200711_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sets',
            new_name='set',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_is_displayed',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='pop',
            name='pop_is_displayed',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=3),
        ),
    ]
