# Generated by Django 3.0.7 on 2020-08-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_auto_20200723_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemDisplayedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDisplayed', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='checklist',
            name='list_of_sets',
            field=models.ManyToManyField(to='list.Set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='items_in_set',
            field=models.ManyToManyField(to='list.Item'),
        ),
        migrations.AlterField(
            model_name='set',
            name='pop_in_set',
            field=models.ManyToManyField(to='list.Pop'),
        ),
    ]
